image: docker:latest
services:
  - docker:dind
stages:
  - build

default:
   before_script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    
step-deploy-compose:
 stage: build
 tags:
    - docker
 only:
    - master
 script:
    - apk add --no-cache docker-compose
    - docker-compose  -f docker-compose.yml build --parallel
    - docker-compose push
