version: '3.4'

services:
  AdminApi:
    image: registry.egov.uz/axad/nissystem:adminapi
    labels:
     NAME: "Admin Api"
    
    build:
      context: .
      dockerfile: AdminApi/Dockerfile
    ports:
     - "6051:6051"
  UserApi:
    image: registry.egov.uz/axad/nissystem:userapi
    labels:
     NAME: "User Api"
    
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:
     - "6052:6052"
  MonitoringApi:
    image: registry.egov.uz/axad/nissystem:monitoringapi
    labels:
     NAME: "Monitoring Api"
    
    build:
      context: .
      dockerfile: MonitoringApi/Dockerfile
    ports:
     - "6053:6053"
